const POSTS = [
  { id:'cot-agent', year:'2024', topic:'LLM reasoning', cover:'../images/fulls/CoT.png', alt:'Chain-of-thought reasoning illustration', source:'https://mp.weixin.qq.com/s/bJYqfHF4RrYS8GkXfOMYGA', titleZh:'从 CoT 到 Agent：最全综述来了', titleEn:'From Chain of Thought to Agents: A Comprehensive Review' },
  { id:'thought-structures', year:'2024', topic:'LLM reasoning', cover:'../images/fulls/CoT2.png', alt:'Reasoning structures illustration', source:'https://mp.weixin.qq.com/s/0VAQudHElb_aqC0TvqvE8Q', titleZh:'拆解思维链、思维树与思维图：如何优化大模型推理能力？', titleEn:'Chains, Trees, and Graphs of Thought: Optimising LLM Reasoning' },
  { id:'zero-initialization', year:'2024', topic:'Machine learning', cover:'../images/fulls/Zero.png', alt:'ZerO initialization visual', source:'https://mp.weixin.qq.com/s/jDyqQfdyRbJ81-Z24OyMYw', titleZh:'忘掉 Xavier 初始化：最强初始化方法 ZerO 来了', titleEn:'Beyond Xavier: Introducing ZerO Initialization' },
  { id:'sora-china', year:'2024', topic:'Generative video', cover:'../images/fulls/Sora.png', alt:'Generative video visual', source:'https://mp.weixin.qq.com/s/45HTCN0ccaV42DOcHSLceQ', titleZh:'国内 Sora 类模型发展到哪了？与 Sora 的差距有多大？', titleEn:'Sora-like Models in China: Progress and the Remaining Gap' },
  { id:'aigc-unicorns', year:'2024', topic:'AI industry', cover:'../images/fulls/Ts.png', alt:'AI industry illustration', source:'https://mp.weixin.qq.com/s/YTzJZ-5_b2W03psYrt0K2Q', titleZh:'今年中国诞生六家 AIGC 独角兽，三家由清华校友领衔', titleEn:'Six AIGC Unicorns Emerged in China This Year' },
  { id:'humanoid-robots', year:'2024', topic:'Robotics', cover:'../images/fulls/robot.png', alt:'Humanoid robot illustration', source:'https://mp.weixin.qq.com/s/4JA-03w5kbs1IUYQ6xMqfg', titleZh:'2024：人形机器人的爆发之年？', titleEn:'2024: The Breakout Year for Humanoid Robots?' },
  { id:'claude-3', year:'2024', topic:'Foundation models', cover:'../images/fulls/claude.png', alt:'Claude 3 visual', source:'https://mp.weixin.qq.com/s/K-HvtY0Wi0m4QoKGQ3v3nA', titleZh:'摆脱 OpenAI 阴影的 Claude 3：赞誉与争议并存', titleEn:'Claude 3 Beyond OpenAI’s Shadow: Praise and Criticism' },
  { id:'ehang-air-taxi', year:'2024', topic:'Aviation', cover:'../images/fulls/drone.png', alt:'Electric air taxi illustration', source:'https://mp.weixin.qq.com/s/ZNQg-HgYrcOkCNWrp7QmSg', titleZh:'无人机上淘宝？亿航首款国产空中出租车开售', titleEn:'An Air Taxi on Taobao: EHang’s Domestic Debut' },
  { id:'superalignment', year:'2024', topic:'AI safety', cover:'../images/fulls/align.png', alt:'AI alignment visual', source:'https://mp.weixin.qq.com/s/zfhkJcCz0F-rdMRW44CoRw', titleZh:'OpenAI 超级对齐团队首篇论文：用 GPT-2 监督 GPT-4', titleEn:'OpenAI Superalignment: Using GPT-2 to Supervise GPT-4' },
  { id:'vidu', year:'2024', topic:'Generative video', cover:'../images/fulls/sora2.png', alt:'Vidu video model illustration', source:'https://mp.weixin.qq.com/s/zPISd1apeChwZ-W49C0LQg', titleZh:'清华团队发布 Vidu：中国首个对标 Sora 的视频大模型', titleEn:'Vidu: China’s Video Model Taking Aim at Sora' },
  { id:'paper-without-code', year:'2024', topic:'Research culture', cover:'../images/fulls/paper.png', alt:'Research paper illustration', source:'https://mp.weixin.qq.com/s/a3vhIKrlyzkfi4vInolumA', titleZh:'PaperWithoutCode：曝光不可复现论文，首作者遭社交冲击？', titleEn:'PaperWithoutCode and the Debate on Irreproducible Research' },
  { id:'simple-methods', year:'2024', topic:'Research culture', cover:'../images/fulls/reject.png', alt:'Paper review illustration', source:'https://mp.weixin.qq.com/s/QwSy2Gh6lzQV8Fuas8pP-Q', titleZh:'仅因方法“太简单”就拒稿，合理吗？', titleEn:'Should a Paper Be Rejected Because Its Method Is “Too Simple”?' },
  { id:'nlp-value', year:'2024', topic:'NLP', cover:'../images/fulls/NLP.png', alt:'Natural language processing illustration', source:'https://mp.weixin.qq.com/s/3zYbSZ-fS1j4ucwfCjFBJw', titleZh:'NLP 哪个子领域的社会价值最高？', titleEn:'Which NLP Subfield Has the Greatest Social Value?' },
  { id:'algorithm-engineers', year:'2024', topic:'Engineering', cover:'../images/fulls/algo.png', alt:'Algorithm engineering illustration', source:'https://mp.weixin.qq.com/s/cVw05WElPWMUK9s6MFig0Q', titleZh:'算法工程师的三观测试', titleEn:'A Three-View Test for Algorithm Engineers' }
];
